const path = require("node:path");

const rootDir = __dirname;
const e = (key, fallback = "") => process.env[key] ?? fallback;
const localhost = e("LOCALHOST_HOST", "127.0.0.1");
const walletDbEnv = {
  DB_HOST: e("DB_HOST", localhost),
  DB_PORT: e("DB_PORT", "5432"),
  DB_USER: e("DB_USER"),
  DB_PASS: e("DB_PASS"),
  DB_NAME: e("DB_NAME", "wallet_platform"),
  DB_SYNC: e("DB_SYNC", "true"),
};

module.exports = {
  apps: [
    {
      name: "auth-service",
      cwd: path.join(rootDir, "auth-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3001",
        GRPC_URL: "0.0.0.0:50051",
        ...walletDbEnv,
        AUTH_DEV_MODE: e("AUTH_DEV_MODE", "true"),
        FIREBASE_PROJECT_ID: e("FIREBASE_PROJECT_ID"),
        FIREBASE_API_KEY: e("FIREBASE_API_KEY"),
        JWT_SECRET: e("JWT_SECRET"),
        JWT_ISSUER: e("JWT_ISSUER", "auth-service"),
        JWT_AUDIENCE: e("JWT_AUDIENCE", "e-wallet"),
        JWT_ACCESS_TTL_SECONDS: e("JWT_ACCESS_TTL_SECONDS", "300"),
        JWT_REFRESH_TTL_SECONDS: e("JWT_REFRESH_TTL_SECONDS", "604800"),
        NOTIFICATION_GRPC_URL: `${localhost}:50055`,
        STEP_UP_EMAIL_OTP_TTL_SECONDS: e("STEP_UP_EMAIL_OTP_TTL_SECONDS", "180"),
      },
    },
    {
      name: "transaction-service",
      cwd: path.join(rootDir, "transaction-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3002",
        GRPC_URL: "0.0.0.0:50052",
        ...walletDbEnv,
        OUTSIDE_PAYMENT_GRPC_URL: `${localhost}:50053`,
        CHAIN_GRPC_URL: `${localhost}:50054`,
        ATO_SERVICE_URL: `http://${localhost}:3010`,
        ATO_TIMEOUT_MS: "250",
        ATO_FAIL_OPEN: "false",
        ATO_TIMEZONE_OFFSET_MINUTES: "420",
        ATO_STATS_CACHE_TTL_MS: "5000",
        ATO_STATS_CACHE_MAX_ENTRIES: "10000",
        KAFKA_ENABLED: "true",
        KAFKA_BROKERS: `${localhost}:9092`,
        KAFKA_TOPIC: "transaction-events",
        WALLET_INITIAL_BALANCE: "10000000",
        CHAIN_RISK_HIGH_AMOUNT: "5000000",
      },
    },
    {
      name: "outside-payment-service",
      cwd: path.join(rootDir, "outside-payment-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3003",
        GRPC_URL: "0.0.0.0:50053",
        ...walletDbEnv,
        EXTERNAL_SETTLE_DELAY_SECONDS: "15",
      },
    },
    {
      name: "chain-service",
      cwd: path.join(rootDir, "chain-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3004",
        GRPC_URL: "0.0.0.0:50054",
        CHAIN_NODE_URL: e("CHAIN_NODE_URL"),
        CHAIN_OBSERVER_URLS: e("CHAIN_OBSERVER_URLS"),
        CHAIN_REQUEST_TIMEOUT_MS: "12000",
        CHAIN_SKIP_TLS_VERIFY: "true",
      },
    },
    {
      name: "notification-service",
      cwd: path.join(rootDir, "notification-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3005",
        GRPC_URL: "0.0.0.0:50055",
        ...walletDbEnv,
        KAFKA_ENABLED: "true",
        KAFKA_BROKERS: `${localhost}:9092`,
        TRANSACTION_EVENTS_TOPIC: "transaction-events",
        KAFKA_CONSUMER_GROUP: "notification-group",
        AUTH_HTTP_URL: `http://${localhost}:3001`,
        SMTP_HOST: e("SMTP_HOST", "smtp.gmail.com"),
        SMTP_PORT: e("SMTP_PORT", "587"),
        SMTP_SECURE: e("SMTP_SECURE", "false"),
        SMTP_USER: e("SMTP_USER"),
        SMTP_PASS: e("SMTP_PASS"),
        SMTP_FROM: e("SMTP_FROM"),
      },
    },
    {
      name: "settlement-service",
      cwd: path.join(rootDir, "settlement-service"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3006",
        TRANSACTION_GRPC_URL: `${localhost}:50052`,
        OUTSIDE_PAYMENT_GRPC_URL: `${localhost}:50053`,
        SETTLEMENT_BATCH_SIZE: "100",
        SETTLEMENT_CONCURRENCY: "20",
        SETTLEMENT_RPC_TIMEOUT_MS: "5000",
        SETTLEMENT_RECONCILE_LIMIT: "500",
        SETTLEMENT_RECONCILE_AUTOFIX: "false",
        SETTLEMENT_ADMIN_TOKEN: e("SETTLEMENT_ADMIN_TOKEN"),
      },
    },
    {
      name: "api-gateway",
      cwd: path.join(rootDir, "api-gateway"),
      script: "npm",
      args: "run start:prod",
      env_production: {
        NODE_ENV: "production",
        PORT: "3000",
        AUTH_HTTP_URL: `http://${localhost}:3001`,
        AUTH_GRPC_URL: `${localhost}:50051`,
        TRANSACTION_GRPC_URL: `${localhost}:50052`,
        NOTIFICATION_GRPC_URL: `${localhost}:50055`,
        JWT_SECRET: e("JWT_SECRET"),
        JWT_ISSUER: e("JWT_ISSUER", "auth-service"),
        JWT_AUDIENCE: e("JWT_AUDIENCE", "e-wallet"),
        RATE_LIMIT_WINDOW_MS: "60000",
        RATE_LIMIT_MAX: "20000",
        RATE_LIMIT_REDIS_URL: "",
        RATE_LIMIT_REDIS_PREFIX: "gw:rl:",
        RISK_HARD_AMOUNT_THRESHOLD: "10000000",
        RISK_ANOMALY_MULTIPLE: "5",
        RISK_MIN_HISTORY_AMOUNT: "1000000",
      },
    },
    {
      name: "ato-service",
      cwd: path.join(rootDir, "ato-service"),
      script: path.join(rootDir, "ato-service", ".venv", "bin", "python"),
      args: "app.py",
      interpreter: "none",
      env: { PYTHONUNBUFFERED: "1" },
    },
    {
      name: "aml-service",
      cwd: path.join(rootDir, "aml-service"),
      script: path.join(rootDir, "aml-service", ".venv", "bin", "python"),
      args: "app.py",
      interpreter: "none",
      env: { PYTHONUNBUFFERED: "1" },
      env_production: {
        PYTHONUNBUFFERED: "1",
        AML_HOST: "0.0.0.0",
        AML_PORT: "3011",
        AML_SCAN_INTERVAL_SECONDS: "86400",
        AML_SCAN_LOOKBACK_HOURS: "24",
        AML_SCAN_LIMIT: "20000",
        AML_SCAN_ON_START: "true",
        AML_SCAN_ONLY_UNSCANNED: "true",
        AML_OVERVIEW_LIMIT: "200000",
        AML_FLAGS_TABLE: "aml_transaction_flags",
        AML_DB_HOST: e("AML_DB_HOST", localhost),
        AML_DB_PORT: e("AML_DB_PORT", "5432"),
        AML_DB_NAME: e("AML_DB_NAME", "wallet_platform"),
        AML_DB_USER: e("AML_DB_USER"),
        AML_DB_PASS: e("AML_DB_PASS"),
        AML_DB_SSLMODE: e("AML_DB_SSLMODE", "prefer"),
      },
    },
  ],
};
