import 'package:flutter/material.dart';

import 'app_settings_service.dart';

class AppLocalizations {
  AppLocalizations._();

  static const supportedLocales = [Locale('vi'), Locale('en')];

  static final Map<String, Map<String, String>> _strings = {
    'vi': {
      'boot_loading': 'Đang tải e-wallet...',
      'login_failed': 'Đăng nhập thất bại',
      'login_title': 'Đăng nhập',
      'login_subtitle': 'Nhập thông tin tài khoản để truy cập ví.',
      'login_identifier': 'Email hoặc số điện thoại',
      'login_identifier_required': 'Vui lòng nhập email hoặc số điện thoại.',
      'login_email_invalid': 'Email không đúng định dạng.',
      'login_phone_invalid': 'Số điện thoại không hợp lệ.',
      'password': 'Mật khẩu',
      'password_required': 'Vui lòng nhập mật khẩu.',
      'password_min': 'Mật khẩu phải có ít nhất 6 ký tự.',
      'login_action': 'Đăng nhập',
      'no_account': 'Chưa có tài khoản? ',
      'sign_up_now': 'Đăng ký ngay',
      'smart_wallet': 'Ví điện tử thông minh',
      'signup_page_title': 'Tạo tài khoản',
      'signup_header': 'Đăng ký Kufi',
      'signup_hint': 'Điền thông tin để bắt đầu',
      'full_name': 'Họ và tên',
      'full_name_required': 'Vui lòng nhập họ tên.',
      'full_name_min': 'Họ tên phải có ít nhất 3 ký tự.',
      'email': 'Email',
      'email_required': 'Vui lòng nhập email.',
      'email_invalid': 'Email không hợp lệ.',
      'phone': 'Số điện thoại',
      'phone_required': 'Vui lòng nhập số điện thoại.',
      'phone_invalid': 'Số điện thoại không hợp lệ.',
      'confirm_password': 'Xác nhận mật khẩu',
      'confirm_password_required': 'Vui lòng xác nhận mật khẩu.',
      'password_mismatch': 'Mật khẩu không khớp.',
      'agree_terms_error': 'Vui lòng đồng ý với điều khoản sử dụng.',
      'agree_with': 'Tôi đồng ý với ',
      'terms_of_use': 'Điều khoản sử dụng',
      'and': ' và ',
      'privacy_policy': 'Chính sách bảo mật',
      'sign_up_action': 'Đăng ký',
      'has_account': 'Đã có tài khoản? ',
      'login_now': 'Đăng nhập',
      'signup_failed': 'Đăng ký thất bại',
      'check_information_error': 'Không thể kiểm tra thông tin lúc này.',
      'phone_in_use': 'Số điện thoại này đã được sử dụng.',
      'email_in_use': 'Email này đã được sử dụng.',
      'email_otp_hint': 'Xác thực email bằng mã OTP để tiếp tục đăng ký.',
      'email_otp_code': 'Mã OTP email',
      'send_otp': 'Gửi mã',
      'resend_after': 'Gửi lại sau {seconds}s',
      'email_otp_required': 'Vui lòng xác thực OTP email trước khi đăng ký.',
      'email_otp_invalid': 'Mã OTP email không chính xác hoặc đã hết hạn.',
      'otp_sent_success': 'OTP đã được gửi qua email.',
      'settings_title': 'Cài đặt',
      'notifications': 'Thông báo',
      'in_app': 'Trong ứng dụng',
      'required': 'Bắt buộc',
      'email_notifications': 'Email',
      'email_notifications_hint': 'Nhận thông báo qua email',
      'sms_notifications': 'SMS',
      'sms_notifications_hint': 'Nhận thông báo qua SMS',
      'feature_in_development': 'Tính năng đang phát triển',
      'appearance': 'Giao diện',
      'light': 'Sáng',
      'light_hint': 'Giao diện mặc định',
      'dark': 'Tối',
      'dark_hint': 'Đỏ đậm trên nền tối',
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'Tiếng Anh',
      'app_info': 'Thông tin ứng dụng',
      'version': 'Phiên bản',
      'blockchain': 'Blockchain',
      'hello': 'Xin chào',
      'secured_by_kufi': 'Bảo mật bởi Kufi',
      'user_generic': 'Người dùng',
      'user_kufi': 'Người dùng Kufi',
      'notification_tooltip': 'Thông báo',
      'logout_tooltip': 'Đăng xuất',
      'wallet_subtitle_default': 'Tài khoản ví điện tử của bạn',
      'wallet_phone_prefix': 'SĐT ví',
      'hidden_recent_transactions_title': 'Giao dịch gần đây đã ẩn',
      'hidden_recent_transactions_hint': 'Mở khóa số dư để xem giao dịch.',
      'nav_home': 'Trang chủ',
      'nav_receipts': 'Hóa đơn',
      'nav_profile': 'Cá nhân',
      'available_balance': 'Số dư khả dụng',
      'hide_balance': 'Ẩn số dư',
      'show_balance': 'Mở số dư',
      'transfer': 'Chuyển tiền',
      'qr_payment': 'QR thanh toán',
      'transaction_utilities': 'Tiện ích giao dịch',
      'topup': 'Nạp tiền',
      'withdraw': 'Rút tiền',
      'spending': 'Chi tiêu',
      'recent_transactions': 'Giao dịch gần đây',
      'hide_transaction_info': 'Ẩn thông tin giao dịch',
      'no_transactions': 'Chưa có giao dịch nào.',
      'linked_funding_source': 'Nguồn tiền liên kết',
      'transaction_partner': 'Đối tác giao dịch',
      'sender': 'Người gửi',
      'recipient': 'Người nhận',
      'deposit_via': 'Nạp tiền qua {provider}',
      'withdraw_via': 'Rút tiền qua {provider}',
      'status_success': 'Thành công',
      'status_failed': 'Thất bại',
      'status_processing': 'Đang xử lý',
      'seconds_ago': '{value} giây trước',
      'minutes_ago': '{value} phút trước',
      'hours_ago': '{value} giờ trước',
      'days_ago': '{value} ngày trước',
      'pin_exact_6': 'PIN gồm đúng 6 chữ số.',
      'pin_incorrect': 'PIN không chính xác.',
      'pin_verify_title': 'Xác thực PIN',
      'pin_unlock_balance_prompt': 'Nhập PIN để mở số dư khả dụng.',
      'secure_pin_label': 'PIN bảo mật',
      'enter_six_digits': 'Nhập đủ 6 chữ số.',
      'cancel': 'Hủy',
      'unlock_balance': 'Mở số dư',
      'pin_unlock_wallet_title': 'Mở khóa ví',
      'pin_unlock_enter_pin': 'Nhập PIN 6 số',
      'relogin': 'Đăng nhập lại',
      'session_expired_unlock': 'Phiên đã hết hạn. Nhập PIN để tiếp tục.',
      'session_expired_login_again':
          'Phiên đã hết hạn. Vui lòng đăng nhập lại.',
    },
    'en': {
      'boot_loading': 'Loading e-wallet...',
      'login_failed': 'Login failed',
      'login_title': 'Login',
      'login_subtitle': 'Enter your account details to access the wallet.',
      'login_identifier': 'Email or phone number',
      'login_identifier_required': 'Please enter your email or phone number.',
      'login_email_invalid': 'Invalid email format.',
      'login_phone_invalid': 'Invalid phone number.',
      'password': 'Password',
      'password_required': 'Please enter your password.',
      'password_min': 'Password must be at least 6 characters.',
      'login_action': 'Login',
      'no_account': 'Don\'t have an account? ',
      'sign_up_now': 'Sign up now',
      'smart_wallet': 'Smart e-wallet',
      'signup_page_title': 'Create account',
      'signup_header': 'Sign up for Kufi',
      'signup_hint': 'Fill in your details to get started',
      'full_name': 'Full name',
      'full_name_required': 'Please enter your full name.',
      'full_name_min': 'Name must have at least 3 characters.',
      'email': 'Email',
      'email_required': 'Please enter your email.',
      'email_invalid': 'Invalid email address.',
      'phone': 'Phone number',
      'phone_required': 'Please enter your phone number.',
      'phone_invalid': 'Invalid phone number.',
      'confirm_password': 'Confirm password',
      'confirm_password_required': 'Please confirm your password.',
      'password_mismatch': 'Passwords do not match.',
      'agree_terms_error': 'Please accept the terms of use.',
      'agree_with': 'I agree with ',
      'terms_of_use': 'Terms of Use',
      'and': ' and ',
      'privacy_policy': 'Privacy Policy',
      'sign_up_action': 'Sign up',
      'has_account': 'Already have an account? ',
      'login_now': 'Login',
      'signup_failed': 'Sign up failed',
      'check_information_error': 'Unable to verify information right now.',
      'phone_in_use': 'This phone number is already in use.',
      'email_in_use': 'This email is already in use.',
      'email_otp_hint': 'Verify your email with OTP to continue sign up.',
      'email_otp_code': 'Email OTP code',
      'send_otp': 'Send code',
      'resend_after': 'Resend in {seconds}s',
      'email_otp_required': 'Please verify email OTP before signing up.',
      'email_otp_invalid': 'Invalid or expired email OTP.',
      'otp_sent_success': 'OTP has been sent to your email.',
      'settings_title': 'Settings',
      'notifications': 'Notifications',
      'in_app': 'In app',
      'required': 'Required',
      'email_notifications': 'Email',
      'email_notifications_hint': 'Receive notifications via email',
      'sms_notifications': 'SMS',
      'sms_notifications_hint': 'Receive notifications via SMS',
      'feature_in_development': 'Feature is under development',
      'appearance': 'Appearance',
      'light': 'Light',
      'light_hint': 'Default appearance',
      'dark': 'Dark',
      'dark_hint': 'Crimson accents on dark background',
      'language': 'Language',
      'vietnamese': 'Vietnamese',
      'english': 'English',
      'app_info': 'App information',
      'version': 'Version',
      'blockchain': 'Blockchain',
      'hello': 'Hello',
      'secured_by_kufi': 'Secured by Kufi',
      'user_generic': 'User',
      'user_kufi': 'Kufi user',
      'notification_tooltip': 'Notifications',
      'logout_tooltip': 'Logout',
      'wallet_subtitle_default': 'Your e-wallet account',
      'wallet_phone_prefix': 'Wallet phone',
      'hidden_recent_transactions_title': 'Recent transactions are hidden',
      'hidden_recent_transactions_hint': 'Unlock balance to view transactions.',
      'nav_home': 'Home',
      'nav_receipts': 'Receipts',
      'nav_profile': 'Profile',
      'available_balance': 'Available balance',
      'hide_balance': 'Hide balance',
      'show_balance': 'Show balance',
      'transfer': 'Transfer',
      'qr_payment': 'QR payment',
      'transaction_utilities': 'Transaction utilities',
      'topup': 'Top up',
      'withdraw': 'Withdraw',
      'spending': 'Spending',
      'recent_transactions': 'Recent transactions',
      'hide_transaction_info': 'Hide transaction details',
      'no_transactions': 'No transactions yet.',
      'linked_funding_source': 'Linked funding source',
      'transaction_partner': 'Transaction partner',
      'sender': 'Sender',
      'recipient': 'Recipient',
      'deposit_via': 'Top up via {provider}',
      'withdraw_via': 'Withdraw via {provider}',
      'status_success': 'Success',
      'status_failed': 'Failed',
      'status_processing': 'Processing',
      'seconds_ago': '{value}s ago',
      'minutes_ago': '{value}m ago',
      'hours_ago': '{value}h ago',
      'days_ago': '{value}d ago',
      'pin_exact_6': 'PIN must be exactly 6 digits.',
      'pin_incorrect': 'Incorrect PIN.',
      'pin_verify_title': 'Verify PIN',
      'pin_unlock_balance_prompt': 'Enter PIN to unlock available balance.',
      'secure_pin_label': 'Security PIN',
      'enter_six_digits': 'Enter all 6 digits.',
      'cancel': 'Cancel',
      'unlock_balance': 'Unlock balance',
      'pin_unlock_wallet_title': 'Unlock wallet',
      'pin_unlock_enter_pin': 'Enter 6-digit PIN',
      'relogin': 'Sign in again',
      'session_expired_unlock': 'Session expired. Enter PIN to continue.',
      'session_expired_login_again': 'Session expired. Please sign in again.',
    },
  };

  static String text(String key, {Map<String, String>? params}) {
    final language = AppSettingsService().language;
    final languageMap = _strings[language] ?? _strings['vi']!;
    var value = languageMap[key] ?? _strings['vi']![key] ?? key;
    params?.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }

  static String pick({required String vi, required String en}) {
    return AppSettingsService().language == 'en' ? en : vi;
  }
}
